create or replace view view_inventory as
	select `p`.`id`                                                                                              AS `id`,
       `p`.`name`                                                                                            AS `name`,
       `p`.`sn`                                                                                              AS `sn`,
       `p`.`color`                                                                                           AS `color`,
       `p`.`size`                                                                                            AS `size`,
       `all_purchase`.`all_purchase_quantity`                                                                AS `all_purchase_quantity`,
       `all_stocktaking`.`all_stocktaking_quantity`                                                          AS `all_stocktaking_quantity`,
       `all_packet`.`all_packet_quantity`                                                                    AS `all_packet_quantity`,
       `all_shipment`.`all_shipment_quantity`                                                                AS `all_shipment_quantity`,
       (((ifnull(`all_purchase`.`all_purchase_quantity`, 0) + ifnull(`all_stocktaking`.`all_stocktaking_quantity`, 0)) -
         ifnull(`all_packet`.`all_packet_quantity`, 0)) -
        ifnull(`all_shipment`.`all_shipment_quantity`, 0))                                                   AS `inventory_quantity`,
       `ontheway_shipment`.`ontheway_shipment_quantity`                                                      AS `ontheway_shipment_quantity`,
       `ontheway_purchase`.`ontheway_purchase_quantity`                                                      AS `ontheway_purchase_quantity`
from ((((((`tbl_product` `p` left join (select `tbl_shipment_detail`.`product_id`    AS `product_id`,
                                                             sum(`tbl_shipment_detail`.`quantity`) AS `all_shipment_quantity`
                                                      from `tbl_shipment_detail`
                                                      where (`tbl_shipment_detail`.`box` <> 'Plan')
                                                      group by `tbl_shipment_detail`.`product_id`) `all_shipment` on ((`p`.`id` = `all_shipment`.`product_id`))) left join (select `tbl_packet_detail`.`product_id`    AS `product_id`,
                                                                                                                                                                                                 sum(`tbl_packet_detail`.`quantity`) AS `all_packet_quantity`
                                                                                                                                                                                          from `tbl_packet_detail`
                                                                                                                                                                                          group by `tbl_packet_detail`.`product_id`) `all_packet` on ((`p`.`id` = `all_packet`.`product_id`))) left join (select `tbl_stocktaking_detail`.`product_id`               AS `product_id`,
                                                                                                                                                                                                                                                                                                                               sum(`tbl_stocktaking_detail`.`adjustment_quantity`) AS `all_stocktaking_quantity`
                                                                                                                                                                                                                                                                                                                        from `tbl_stocktaking_detail`
                                                                                                                                                                                                                                                                                                                        group by `tbl_stocktaking_detail`.`product_id`) `all_stocktaking` on ((`p`.`id` = `all_stocktaking`.`product_id`))) left join (select `tbl_purchase_detail`.`product_id`             AS `product_id`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sum(`tbl_purchase_detail`.`received_quantity`) AS `all_purchase_quantity`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     from `tbl_purchase_detail`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     group by `tbl_purchase_detail`.`product_id`) `all_purchase` on ((`p`.`id` = `all_purchase`.`product_id`))) left join (select `tbl_shipment_detail`.`product_id`    AS `product_id`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sum(`tbl_shipment_detail`.`quantity`) AS `ontheway_shipment_quantity`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         from (`tbl_shipment_detail`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  left join `tbl_shipment`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            on ((`tbl_shipment_detail`.`shipment_id` =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 `tbl_shipment`.`id`)))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         where ((`tbl_shipment_detail`.`box` <> 'Plan') and
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (isnull(`tbl_shipment`.`signed_date`) or
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 (`tbl_shipment`.`signed_date` = '')))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         group by `tbl_shipment_detail`.`product_id`) `ontheway_shipment` on ((`p`.`id` = `ontheway_shipment`.`product_id`)))
         left join (select `tbl_purchase_detail`.`product_id`               AS `product_id`,
                           (sum(`tbl_purchase_detail`.`book_quantity`) -
                            sum(`tbl_purchase_detail`.`received_quantity`)) AS `ontheway_purchase_quantity`
                    from (`tbl_purchase_detail`
                             left join `tbl_purchase`
                                       on ((`tbl_purchase_detail`.`purchase_id` =
                                            `tbl_purchase`.`id`)))
                    where (isnull(`tbl_purchase`.`received_date`) or
                           (`tbl_purchase`.`received_date` = ''))
                    group by `tbl_purchase_detail`.`product_id`) `ontheway_purchase`
                   on ((`p`.`id` = `ontheway_purchase`.`product_id`)));